site_name: Ultralytics Docs
repo_url: https://github.com/ultralytics/ultralytics
edit_uri: https://github.com/ultralytics/ultralytics/tree/main/docs
repo_name: ultralytics/ultralytics

theme:
  name: "material"
  logo: https://github.com/ultralytics/assets/raw/main/logo/Ultralytics-logomark-white.png
  favicon: assets/favicon.ico
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.expand
    - navigation.footer

extra_css:
  - stylesheets/style.css

markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - def_list
  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Button
  - attr_list

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - mkdocstrings
  - search

# Primary navigation
nav:
  - Quickstart: quickstart.md
  - CLI: cli.md
  - Python Interface: sdk.md
  - Configuration: config.md
  - Customization Guide: engine.md
  - Ultralytics HUB: hub.md
  - iOS and Android App: app.md
  - Reference:
      - Python Model interface: reference/model.md
      - Engine:
          - Trainer: reference/base_trainer.md
          - Validator: reference/base_val.md
          - Predictor: reference/base_pred.md
          - Exporter: reference/exporter.md
      - nn Module: reference/nn.md
      - operations: reference/ops.md
